# Generated by Django 2.0.9 on 2019-01-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190110_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='blue', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category'),
        ),
    ]
